name: 'Github Release Action'
author: 'Suger Inc'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
description: 'Publish Github releases from an action'
env:
  GITHUB_TOKEN: 'The Github Token'
inputs:
  commit_message:
    description: 'The commit message to publish'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.commit_message }}